openapi: 3.0.3

info:
  title: CSES API
  description: API describing the communication between CSES CLI and cses.fi
  version: 0.0.1

# define possible authentication methods
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      x-basicInfoFunc: app.basic_auth

    cookieAuth: # could be any name
      type: apiKey
      in: cookie # where should this be?
      name: SESSIONID

security:
  - cookieAuth: []

paths:
  /login:
    get:
      # unique id for mocking

      operationId: app.login_get
      summary: Logs in the user with CSES credentials

      security:
        - basicAuth: []

      responses:
        "200":
          description: >
            Authentication successful. The SESSIONID is returned as a
            json object.
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                required:
                  - sessionid
                properties:
                  sessionid:
                    type: string

              examples:
                # for documentations and
                # could be used by the prism
                example1:
                  summary: An example session ID
                  value:
                    sessionid: "123"

        "401":
          description: Invalid username/password.
