openapi: 3.0.3

info:
  title: CSES API
  description: API describing the communication between CSES CLI and cses.fi
  version: 0.0.1
  license:
    name: MIT
    url: https://github.com/H4m5t3r/cses-cli/blob/main/LICENSE

components:
  schemas:
    $ref: "schemas.yaml"
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-Auth-Token
      x-apikeyInfoFunc: app.apikey_auth

paths:
  /login:
    post:
      # unique id for mocking
      operationId: app.login_post

      summary: Start login flow
      description: >
        Request a new API token and authentication URL corresponding to it.
        In order to complete the flow, the end user should be instructed to
        visit the URL and log in.

      security: []

      responses:
        "200":
          description: >
            Request successful. X-Auth-Token and authentication URL are returned
            as JSON.
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                required:
                  - X-Auth-Token
                  - authentication_url
                properties:
                  X-Auth-Token:
                    description: API token that can be used to authorize the user.
                    type: string
                  authentication_url:
                    description: URL the user should visit to log in.
                    type: string

        "4XX":
          $ref: "responses.yaml#/ClientError"

        "5XX":
          $ref: "responses.yaml#/ServerError"

    get:
      operationId: app.login_get

      summary: Get login status
      description: >
        Request information about a given X-Auth-Token. The response is successful
        if the API token is valid, a `PendingApiKeyError` when the token has not
        yet been authenticated, and an `InvalidApiKeyError` otherwise.

      security:
        - apiKeyAuth: []

      responses:
        "200":
          description: >
            Login is valid. User information given in response.
          content:
            application/json:
              schema:
                $ref: "schemas.yaml#/UserOutline"

        "401":
          $ref: "responses.yaml#/GetLoginError"

        "4XX":
          $ref: "responses.yaml#/ClientError"

        "5XX":
          $ref: "responses.yaml#/ServerError"

  /logout:
    post:
      operationId: app.logout_post

      summary: Deauthorizes the given authorization token.
      description: >
        Deauthorizes the valid authentication token. Returns if the
        deauthorization was successful or not.

      security:
        - apiKeyAuth: []

      responses:
        "204":
          description: Api token deauthorized successfully.

        "401":
          $ref: "responses.yaml#/InvalidApiKeyError"

        "4XX":
          $ref: "responses.yaml#/ClientError"

        "5XX":
          $ref: "responses.yaml#/ServerError"

  /courses/{course_id}/submissions:
    post:
      operationId: app.courses_submissions_post

      summary: Make new course submission.

      tags:
        - courses

      description: >
        Submit code file encoded as base64.

      security:
        - apiKeyAuth: []

      parameters:
        - $ref: "parameters.yaml#/CourseId"
        - $ref: "parameters.yaml#/OptionalTaskId"

      requestBody:
        $ref: 'request_bodies.yaml#/SubmissionBody'

      responses:
        "200":
          $ref: "responses.yaml#/SuccessfulCourseSubmissionPost"
        "400":
          $ref: "responses.yaml#/SubmissionClientError"
        "4XX":
          $ref: "responses.yaml#/ClientError"
        "5XX":
          $ref: "responses.yaml#/ServerError"

    get:
      operationId: app.courses_get_submission_list

      summary: Retrieve information about submissions on a course task.

      tags:
        - courses

      security:
        - apiKeyAuth: []

      parameters:
        - $ref: "parameters.yaml#/CourseId"
        - $ref: "parameters.yaml#/TaskId"

      responses:
        "200":
          $ref: "responses.yaml#/SuccessfulCourseSubmissionListGet"
        "4XX":
          $ref: "responses.yaml#/ClientError"
        "5XX":
          $ref: "responses.yaml#/ServerError"

  /contests/{contest_id}/submissions:
    post:
      operationId: app.contests_submissions_post

      summary: Make new contest submission.

      tags:
        - contests

      description: >
        Submit code file encoded as base64.

      security:
        - apiKeyAuth: []

      parameters:
        - $ref: "parameters.yaml#/ContestId"
        - $ref: "parameters.yaml#/OptionalTaskId"

      requestBody:
        $ref: 'request_bodies.yaml#/SubmissionBody'

      responses:
        "200":
          $ref: "responses.yaml#/SuccessfulContestSubmissionPost"
        "400":
          $ref: "responses.yaml#/SubmissionClientError"
        "4XX":
          $ref: "responses.yaml#/ClientError"
        "5XX":
          $ref: "responses.yaml#/ServerError"

    get:
      operationId: app.contests_get_submission_list

      summary: Retrieve information about submissions on a contests task.

      tags:
        - contests

      security:
        - apiKeyAuth: []

      parameters:
        - $ref: "parameters.yaml#/ContestId"
        - $ref: "parameters.yaml#/TaskId"

      responses:
        "200":
          $ref: "responses.yaml#/SuccessfulContestSubmissionListGet"
        "4XX":
          $ref: "responses.yaml#/ClientError"
        "5XX":
          $ref: "responses.yaml#/ServerError"

  /courses/{course_id}/submissions/{submission_id}:
    get:
      operationId: app.courses_get_submission

      summary: Retrieve information about a course submission.

      tags:
        - courses

      security:
        - apiKeyAuth: []

      parameters:
        - $ref: "parameters.yaml#/CourseId"
        - $ref: "parameters.yaml#/SubmissionId"
        - $ref: "parameters.yaml#/LongPoll"

      responses:
        "200":
          $ref: "responses.yaml#/SuccessfulCourseSubmissionInfoGet"
        "4XX":
          $ref: "responses.yaml#/ClientError"
        "5XX":
          $ref: "responses.yaml#/ServerError"

  /contests/{contest_id}/submissions/{submission_id}:
    get:
      operationId: app.contests_get_submission

      summary: Retrieve information about a contest submission.

      tags:
        - contests

      security:
        - apiKeyAuth: []

      parameters:
        - $ref: "parameters.yaml#/ContestId"
        - $ref: "parameters.yaml#/SubmissionId"
        - $ref: "parameters.yaml#/LongPoll"

      responses:
        "200":
          $ref: "responses.yaml#/SuccessfulContestSubmissionInfoGet"
        "4XX":
          $ref: "responses.yaml#/ClientError"
        "5XX":
          $ref: "responses.yaml#/ServerError"

  /courses:
    get:
      operationId: app.get_courses

      summary: Retrieve information about the available courses.

      tags:
        - courses

      security:
        - apiKeyAuth: []
        - {}

      responses:
        "200":
          $ref: "responses.yaml#/SuccessfulCourseListGet"
        "4XX":
          $ref: "responses.yaml#/ClientError"
        "5XX":
          $ref: "responses.yaml#/ServerError"

  /courses/{course_id}/list:
    get:
      operationId: app.get_course_content

      summary: Retrieve the listed information related to a course.

      tags:
        - courses

      security:
        - apiKeyAuth: []
        - {}

      parameters:
        - $ref: "parameters.yaml#/CourseId"

      responses:
        "200":
          $ref: "responses.yaml#/SuccessfulCourseContentGet"
        "4XX":
          $ref: "responses.yaml#/ClientError"
        "5XX":
          $ref: "responses.yaml#/ServerError"

  /contests/{contest_id}/list:
    get:
      operationId: app.get_contest_content

      summary: Retrieve the listed information related to a contest.

      tags:
        - contests

      security:
        - apiKeyAuth: []
        - {}

      parameters:
        - $ref: "parameters.yaml#/ContestId"

      responses:
        "200":
          $ref: "responses.yaml#/SuccessfulContestContentGet"
        "4XX":
          $ref: "responses.yaml#/ClientError"
        "5XX":
          $ref: "responses.yaml#/ServerError"

  /courses/{course_id}/statement:
    get:
      operationId: app.get_course_task_statement

      summary: Retrieve a task statement related to a task in a course.

      tags:
        - courses

      security:
        - apiKeyAuth: []
        - {}

      parameters:
        - $ref: "parameters.yaml#/CourseId"
        - $ref: "parameters.yaml#/TaskId"

      responses:
        "200":
          $ref: "responses.yaml#/SuccessfulTaskStatementGet"
        "4XX":
          $ref: "responses.yaml#/ClientError"
        "5XX":
          $ref: "responses.yaml#/ServerError"

  /contests/{contest_id}/statement:
    get:
      operationId: app.get_contest_task_statement

      summary: Retrieve a task statement related to a task in a contest.

      tags:
        - contests

      security:
        - apiKeyAuth: []
        - {}

      parameters:
        - $ref: "parameters.yaml#/ContestId"
        - $ref: "parameters.yaml#/TaskId"

      responses:
        "200":
          $ref: "responses.yaml#/SuccessfulTaskStatementGet"
        "4XX":
          $ref: "responses.yaml#/ClientError"
        "5XX":
          $ref: "responses.yaml#/ServerError"

  /courses/{course_id}/templates:
    get:
      operationId: app.courses_get_template

      summary: Retrieve a code template.

      tags:
        - courses

      description: >
        Requests a code template matching the given parameters.
        The server decides whether some code template matches the
        given parameters or not.

      security:
        - apiKeyAuth: []
        - {}

      parameters:
        - $ref: "parameters.yaml#/CourseId"
        - $ref: "parameters.yaml#/OptionalTaskId"
        - $ref: "parameters.yaml#/OptionalTemplateFilename"
        - $ref: "parameters.yaml#/OptionalProgrammingLanguage"

      responses:
        "200":
          $ref: "responses.yaml#/SuccessfulCodeTemplateGet"
        "4XX":
          $ref: "responses.yaml#/ClientError"
        "5XX":
          $ref: "responses.yaml#/ServerError"

  /contests/{contest_id}/templates:
    get:
      operationId: app.contests_get_template

      summary: Retrieve a code template.

      tags:
        - contests

      description: >
        Requests a code template matching the given parameters.
        The server decides whether some code template matches the
        given parameters or not.

      security:
        - apiKeyAuth: []
        - {}

      parameters:
        - $ref: "parameters.yaml#/ContestId"
        - $ref: "parameters.yaml#/OptionalTaskId"
        - $ref: "parameters.yaml#/OptionalTemplateFilename"
        - $ref: "parameters.yaml#/OptionalProgrammingLanguage"

      responses:
        "200":
          $ref: "responses.yaml#/SuccessfulCodeTemplateGet"
        "4XX":
          $ref: "responses.yaml#/ClientError"
        "5XX":
          $ref: "responses.yaml#/ServerError"

  /courses/{course_id}/samples:
    get:
      operationId: app.course_get_samples

      summary: Retrieve sample test cases.

      tags:
        - courses

      description: >
        Requests sample test cases for a task on a course.
        Order of the test cases should be the same as on the 
        task statement.

      security:
        - apiKeyAuth: []
        - {}

      parameters:
        - $ref: "parameters.yaml#/CourseId"
        - $ref: "parameters.yaml#/TaskId"

      responses:
        "200":
          $ref: "responses.yaml#/SuccessfulSamplesGet"
        "4XX":
          $ref: "responses.yaml#/ClientError"
        "5XX":
          $ref: "responses.yaml#/ServerError"

  /contests/{contest_id}/samples:
    get:
      operationId: app.contest_get_samples

      summary: Retrieve sample test cases.

      tags:
        - contests

      description: >
        Requests sample test cases for a task on a contest.
        Order of the test cases should be the same as on the 
        task statement.

      security:
        - apiKeyAuth: []
        - {}

      parameters:
        - $ref: "parameters.yaml#/ContestId"
        - $ref: "parameters.yaml#/TaskId"

      responses:
        "200":
          $ref: "responses.yaml#/SuccessfulSamplesGet"
        "4XX":
          $ref: "responses.yaml#/ClientError"
        "5XX":
          $ref: "responses.yaml#/ServerError"
