openapi: 3.0.3

info:
  title: CSES API
  description: API describing the communication between CSES CLI and cses.fi
  version: 0.0.1
  license:
    name: MIT
    url: https://github.com/H4m5t3r/cses-cli/blob/main/LICENSE

components:
  responses:
    InvalidApiKeyError:
      description: Invalid api key error response from the server.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/InvalidApiKeyError"

    InvalidCredentialsError:
      description: Invalid credentials error response from the server.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/InvalidCredentialsError"

    ClientError:
      description: General error response from the server.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ClientError"
          examples:
            example1:
              summary: An example error message
              value:
                message: Too many requests
                code: client_error

    ServerError:
      description: General server error.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ServerError"

  schemas:
    BaseError:
      additionalProperties: false
      required:
        - message
        - code
      type: object

      properties:
        message:
          description: Human-readable error message from the server.
          type: string
        code:
          description: Machine-readable error code from the server.
          type: string
          enum:
            - invalid_api_key
            - invalid_credentials
            - server_error
            - client_error

    InvalidApiKeyError:
      allOf:
        - $ref: "#/components/schemas/BaseError"
        - type: object
          properties:
            code:
              type: string
              enum:
                - invalid_api_key

    InvalidCredentialsError:
      allOf:
        - $ref: "#/components/schemas/BaseError"
        - type: object
          properties:
            code:
              type: string
              enum:
                - invalid_credentials

    ClientError:
      allOf:
        - $ref: "#/components/schemas/BaseError"
        - type: object
          properties:
            code:
              type: string
              enum:
                - client_error

    ServerError:
      allOf:
        - $ref: "#/components/schemas/BaseError"
        - type: object
          properties:
            code:
              type: string
              enum:
                - server_error

    Language:
      additionalProperties: false
      required:
        - name
        - option
      type: object

      properties:
        name:
          type: string
          description: >
            Name of the language, e.g. "C++", "Haskell", "Python2".
        option:
          type: string
          nullable: true
          description: >
            Optional language version specifier, e.g. "CPython" or "PyPy".

    TestProgress:
      additionalProperties: false
      required:
        - finished_tests
        - total_tests
      type: object

      properties:
        finished_tests:
          type: integer
          minimum: 0
          description: >
            The number of finished tests.
        total_tests:
          type: integer
          minimum: 0
          description: >
            The total number of tests.

    SubmissionInfo:
      additionalProperties: false
      required:
        - time
        - language
        - status
        - pending
      type: object

      properties:
        time:
          type: string
          format: date-time
          description: >
            Submission time in ISO 8601 format. (Timezone format has not been decided upon)
        language:
          $ref: "#/components/schemas/Language"
        status:
          type: string
          description: >
            Status of the submission, e.g. "PENDING" or "READY".
        pending:
          type: boolean
          description: >
            Whether the submission is still being graded,
            and the information may change soon.
        test_progress:
          description: >
            > An optional property describing the progress of the testing phase.
          $ref: "#/components/schemas/TestProgress"
        result:
          type: string
          description: >
            Verdict of the submission, e.g. "ACCEPTED".
        tests:
          type: array
          items:
            type: object
            additionalProperties: false
            required:
              - number
              - verdict
              - time
            properties:
              number:
                type: integer
                description: Test case number, starting from 1.
              verdict:
                type: string
                description: >
                  Verdict of the test, e.g. "WRONG ANSWER".
              time:
                type: integer
                description: Run time of the test in milliseconds.
        compiler:
          type: string
          description: >
            The compiler report in case of COMPILE ERROR or just some warnings
            from the compiler.

  parameters:
    CourseId:
      in: path
      name: course_id
      schema:
        type: string
      required: true
      description: >
        Alphanumeric identifier of the course. Same as in course URLs.

    TaskId:
      in: path
      name: task_id
      schema:
        type: integer
      required: true
      description: Task ID.

    SubmissionId:
      in: path
      name: submission_id
      schema:
        type: integer
      required: true
      description: Submission ID.

  # define possible authentication methods
  securitySchemes:
    apiKeyAuth: # could be any name
      type: apiKey
      in: header
      name: X-Auth-Token
      x-apikeyInfoFunc: app.apikey_auth

security:
  - apiKeyAuth: []

paths:
  /login:
    post:
      # unique id for mocking
      operationId: app.login_post

      summary: Logs in the user with CSES credentials
      description: >
        Logs the user in with CSES credentials. Returns an API token
        that can be used to authenticate subsequent API queries.

      security: []

      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - username
                - password
              additionalProperties: false

              type: object
              properties:
                username:
                  description: A CSES username
                  type: string
                password:
                  description: A CSES password
                  type: string
                  format: password

      responses:
        "200":
          description: >
            Authentication successful. X-Auth-Token is returned as a
            json object.
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                required:
                  - X-Auth-Token
                properties:
                  X-Auth-Token:
                    description: API token used to authenticate the user.
                    type: string

        "401":
          $ref: "#/components/responses/InvalidCredentialsError"

        "4XX":
          $ref: "#/components/responses/ClientError"

        "5XX":
          $ref: "#/components/responses/ServerError"

  /logout:
    post:
      operationId: app.logout_post

      summary: Deauthorizes the given authorization token.
      description: >
        Deauthorizes the valid authentication token. Returns if the
        deauthorization was successful or not.

      security:
        - apiKeyAuth: []

      responses:
        "204":
          description: Api token deauthorized successfully.

        "401":
          $ref: "#/components/responses/InvalidApiKeyError"

        "4XX":
          $ref: "#/components/responses/ClientError"

        "5XX":
          $ref: "#/components/responses/ServerError"
  /courses/{course_id}/tasks/{task_id}/submissions:
    post:
      operationId: app.submissions_post

      summary: Make new submission.
      description: >
        Submit code file encoded as base64..

      security:
        - apiKeyAuth: []

      parameters:
        - $ref: "#/components/parameters/CourseId"
        - $ref: "#/components/parameters/TaskId"

      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - language
                - filename
                - content
              additionalProperties: false

              type: object
              properties:
                language:
                  $ref: "#/components/schemas/Language"
                filename:
                  type: string
                  description: Original name of the file.
                content:
                  type: string
                  format: byte
                  description: Content of the file encoded as base64.
      responses:
        "200":
          description: >
            Submission was sent successfully. The new submission ID is
            given in the response.
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                additionalProperties: false
                properties:
                  id:
                    description: ID of the resulting submission.
                    type: integer
        "4XX":
          $ref: "#/components/responses/ClientError"
        "5XX":
          $ref: "#/components/responses/ServerError"

  /courses/{course_id}/tasks/{task_id}/submissions/{submission_id}:
    get:
      operationId: app.get_submission

      summary: Retrieve information about a submission.

      security:
        - apiKeyAuth: []

      parameters:
        - $ref: "#/components/parameters/CourseId"
        - $ref: "#/components/parameters/TaskId"
        - $ref: "#/components/parameters/SubmissionId"
        - in: query
          name: poll
          schema:
            type: boolean
            default: false
          description: >
            Whether or not to use long polling. If set to `true` and the
            submission is still pending, the server will wait up to some
            amount of time, before responding with a result. If grading of
            this submission completes during this time, the response is
            sent immediately.

      responses:
        "200":
          description: >
            Info about a submission is retrieved successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubmissionInfo"
        "4XX":
          $ref: "#/components/responses/ClientError"
        "5XX":
          $ref: "#/components/responses/ServerError"
