name: Coverage report

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  coverage:
    name: Generate coverage report
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache Cargo registry
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/git
          ~/.cargo/registry
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Rust toolchain setup
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: llvm-tools-preview
    - name: Install grcov
      run: if [[ ! -e ~/.cargo/bin/grcov ]]; then cargo install grcov; fi

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Poetry
      uses: snok/install-poetry@v1.1.6
      with:
        virtualenvs-create: true
        virtualenvs-in-project: false
    - name: Cache pip wheels
      uses: actions/cache@v2
      with:
        path: ~/.cache
        key: wheels-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
    - name: Install Poetry dependencies
      run: poetry install --no-interaction
      working-directory: api/mock_server

    - name: Run tests
      run: cargo test --no-default-features
      env:
        RUSTFLAGS: '-Z instrument-coverage -C link-dead-code -C codegen-units=1 -C opt-level=0'
    - name: Run grcov
      run: grcov . --binary-path target/debug/deps/ -s . -t lcov --ignore-not-existing --ignore 'src/test/*' -o coverage.lcov
    - uses: codecov/codecov-action@v1
