name: Openapi documentation generation

on:
  push:
    branches: [main]

  # for testing
  pull_request:
    branches: [main]

jobs:
  docgen:
    name: Generate Openapi documentation
    runs-on: ubuntu-latest
    steps:
      uses: Legion2/swagger-ui-action@v1
      with:
        output: swagger-ui
        spec-file: api/openapi.yaml
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: swagger-ui
